# disable sudo to speed up build
sudo: false

language: python

# python versions to build against
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  
# command to install dependencies
install:
  - pip install py-irt
  - pip install codecov
  - pip install pytest-cov
  
# command to run tests
script:
  - pytest --cov=./

# push results to codecov
after_success:
  - codecov 
